name: Mooses-Wardrobe
version: '0.1'
main: me.plainioldmoose.mooseswardrobe.Wardrobe
api-version: '1.20'
commands:
  wardrobe:
    description: "Open a wardrobe"
    usage: "/wardrobe"
    aliases: [ wr ]
    permission: wardrobe.open
    permission-message: "You do not have permission to open a wardrobe"